config/routes.rb
Rails.application.routes.draw do
  
  get "/sports", to: "sports#index"
  post "/sports", to: "sports#create"
  get "/sports/new", to: "sports#new" , as: "new_sport"
  get "/sports/:id/edit", to: "sports#edit", as: "edit_sport"
  get "/sports/:id", to: "sports#show", as: "sport"
  patch "/sports/:id", to: "sports#update"
  delete "/sports/:id", to: "sports#destroy"
  
  
  
  devise_for :views
  devise_for :users
  root to: 'sports#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sport.rb
class Sport < ApplicationRecord
  validates :year, presence: true
  validates :month, presence: true
  validates :name1, presence: true
  validates :name2, presence: true
  validates :result, presence: true
  
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :sports
  
  
  
  #validates :email, presence: true, uniqueness: true, length: {maximum: 50}
  
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
    
    before_action :set_sport, only: [:show, :edit]
    
    def index
        p current_user
        @sports = current_user.sports
        
    end
    
    def show
    end
    
    def new
        @sport = Sport.new
    end
    
    def create
        @sport = Sport.new(sport_params)
        @sport[:user_id] = current_user.id
        p @sport
        if @sport.save
            flash[:notice] = "データを1件登録しました"
            redirect_to sports_path
        else
            flash.now[:alert] = "登録に失敗しました"
            render :new
        end
    end
    
    def edit
    end
    
    def update
        @sport = Sport.find(params[:id])
        if @sport.update(sport_params)
            flash[:notice] = "データを1件更新しました"
            redirect_to sports_path
        else
            flash.now[:alert] = "更新に失敗しました。"
            render :edit
        end
    end
    
    def destroy
        @sport = current_user.sports.find(params[:id])
        @sport.destroy
        flash[:notice] = "削除しました"
        redirect_to sports_path
    end
    
    private
    
    def set_sport
        @sport = Sport.where(user_id: current_user.id).find(params[:id])
    end
    
    def sport_params
        params.require(:sport).permit(:year, :month, :name1, :name2, :result)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fight</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navber navber-light bg-light">
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, class: 'navbar-link'  %>
        <% end %>
      </p>
    </nav>
      <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <%= flash[:alert] %>
    </div>
    <% end %>
    
    <%= yield %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/sports/edit.html.erb
<h1>更新</h1>

<%= form_with model: @sport, local: true, method: "patch" do |f| %>

<div class="form-group">
    <label>年度</label>
    <%= f.number_field :year, class: "form-control" %>
</div>

<div class="form-group">
    <label>月</label>
    <%= f.number_field :month, class: "form-control" %>
</div>

<div class="form-group">
    <label>赤コーナー</label>
    <%= f.text_field :name1, class: "form-control" %>
</div>
<div class="form-group">
    <label>青コーナー</label>
    <%= f.text_field :name2, class: "form-control" %>
</div>
<div class="form-group">
    <label>勝者</label>
    <%= f.select :result, ["赤コーナー", "青コーナー"] , {}, {class: "form-control"} %>
</div>
<%= link_to "戻る", sports_path, class: "btn btn-secondary" %>
<%= f.submit "更新", class: "btn btn-primary"%>
<% end %>

app/views/sports/index.html.erb
<h1>試合結果</h1>


<div class="card">
  <div class="card-body">
    <%= form_with method: "get", local: true do |f| %>
      <div class="form-row">
          <div class="col">
              <%= f.number_field "year", placeholder: "年度を入力", class: "form-control" %>
          </div>
          <div class="col">
              <%= f.number_field "month", placeholder: "対象月を入力", class: "form-control" %>
          </div>
          <div class="col">
              <%= f.text_field "name1", placeholder: "赤コーナー", class: "form-control" %>
          </div>
          <div class="col">
              <%= f.text_field "name2", placeholder: "青コーナー", class: "form-control" %>
          </div>
          <div class="col">
              <%= f.submit "検索", class: "btn btn-dark" %>
          </div>
      </div>
    <% end %>
  </div>
</div>

<%= link_to "新規", new_sport_path, class: "btn btn-dark" %>
<table class="table table-dark table-striped">
    <tr>
        <th>年月</th>
        <th>赤　　　青</th>
        <th>勝者</th>
        <th>リンク</th>
    </tr>
    <% @sports.each do |sport| %>
    <tr>
        <td><%= sport.year %>年<%= sport.month %>月</td>
        <td><%= sport.name1 %> VS <%= sport.name2 %></td>
        <td><%= sport.result %></td>
        <td>
            <%= link_to "詳細", sport_path(sport), class: "btn btn-light" %>
            <%= link_to "編集", edit_sport_path(sport), class: "btn btn-light" %>
            <%= link_to "削除", sport_path(sport), method: "delete", data: { confirm: '本当に削 除しますか?' }, class: "btn btn-light" %>
        </td>
    </tr>
    <% end %>
</table>

app/views/sports/new.html.erb
<h1>試合結果登録</h1>

<%= form_with model: @sport, local: true do |f| %>

<div class="form-group">
    <label>年度</label>
    <%= f.number_field :year, class: "form-control" %>
</div>

<div class="form-group">
    <label>月</label>
    <%= f.number_field :month, class: "form-control" %>
</div>

<div class="form-group">
    <label>赤コーナー</label>
    <%= f.text_field :name1, class: "form-control" %>
</div>
<div class="form-group">
    <label>青コーナー</label>
    <%= f.text_field :name2, class: "form-control" %>
</div>
<div class="form-group">
    <label>勝者</label>
    <%= f.select :result, ["赤コーナー", "青コーナー"] , {}, {class: "form-control"} %>
</div>
<%= link_to "戻る", sports_path, class: "btn btn-secondary" %>
<%= f.submit "登録", class: "btn btn-primary"%>
<% end %>

app/views/sports/show.html.erb
<h1>詳細</h1>
<table class="table table-dark table-striped">
    <tr>
        <th>年月</th>
        <td><%= @sport.year %>年<%= @sport.month %>月</td>
    </tr> 
    <tr>
        <th>赤VS青</th>
        <td><%= @sport.name1 %>VS<%= @sport.name2 %></td>
    </tr>
    <tr>
        <th>勝者</th>
        <td><%= @sport.result %></td>
    </tr>
</table>
<%= link_to "戻る", sports_path, class: "btn btn-secondary" %>